# Generated by Django 5.2.18 on 2026-10-08 20:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idle_threshold_s', models.PositiveIntegerField(default=600, validators=[django.core.validators.MinValueValidator(60)])),
                ('offline_timeout_s', models.PositiveIntegerField(default=180, validators=[django.core.validators.MinValueValidator(60)])),
                ('heartbeat_interval_s', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(3600)])),
                ('agents_enabled', models.BooleanField(default=True, help_text='Untick to make every agent exit at its next heartbeat (remote off switch).')),
                ('allow_new_pcs', models.BooleanField(default=False, help_text='Tick while setting up so new PCs can register themselves with their first heartbeat; untick afterwards.')),
            ],
            options={
                'verbose_name': 'café settings',
                'verbose_name_plural': 'café settings',
            },
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32, unique=True)),
                ('label', models.CharField(blank=True, max_length=64)),
                ('mac', models.CharField(blank=True, max_length=17)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide from the dashboard.')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_event', models.CharField(blank=True, max_length=16)),
                ('idle_s_at_last_seen', models.PositiveIntegerField(default=0)),
                ('boot_id', models.CharField(blank=True, max_length=64)),
                ('agent_version', models.CharField(blank=True, max_length=32)),
                ('state', models.CharField(choices=[('in_use', 'In use'), ('idle', 'Idle'), ('off', 'Off')], default='off', max_length=8)),
                ('state_since', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PC',
                'ordering': ['label', 'hostname'],
            },
        ),
        migrations.CreateModel(
            name='StateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(choices=[('in_use', 'In use'), ('idle', 'Idle'), ('off', 'Off')], max_length=8)),
                ('to_state', models.CharField(choices=[('in_use', 'In use'), ('idle', 'Idle'), ('off', 'Off')], max_length=8)),
                ('at', models.DateTimeField()),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_changes', to='status.pc')),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['pc', 'at'], name='status_stat_pc_id_360c92_idx')],
            },
        ),
    ]
